export const FETCH_PLAYERS_REQUEST = "FETCHFETCH_PLAYERS_REQUEST_PLAYERS";
export const FETCH_PLAYERS_SUCCESS = "FETCH_PLAYERS_SUCCESS";
export const FETCH_PLAYERS_FAILURE = "FETCH_PLAYERS_FAILURE";
export const WICKET_KEEPER = "WICKET_KEEPER";
export const ALL_ROUNDERS = "ALL_ROUNDERS";
export const BATSMAN = "BATSMAN";
export const BOWLER = "BOWLER";